name: Linux
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
         printenv | sort 
  build-64:
    runs-on: ubuntu-24.04
    steps:
      - run: |
         printenv | sort
