name: Linux
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          printenv | sort
      - run: |
          ls -la /opt/post-generation
      - run: |
          rm -rf /opt/post-generation
          rm -rf /opt/post-generation2
      - run: |
          ls -la /opt/post-generation
      - run: |
          cat /etc/passwd
