name: Linux
on:
  push:
  workflow_dispatch:

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          printenv | sort
      - run: |
          from="/home/runneradmin"
          to='$HOME'
          sed -i "s|\$from|$to|g" /etc/environment
      - run: |
          cat /etc/environment
      - run: |
          homeDir="/home/$RUNNER_USER"
          sed -i "s|\$HOME|$homeDir|g" /etc/environment

          userId=$(id -u $RUNNER_USER)
          echo "User ID: $userId"
          loginctl enable-linger $userId
      - run: |
         cat /etc/environment
      - run: |
          rm -rf /opt/post-generation
          rm -rf /opt/post-generation
