name: Linux
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          printenv | sort
      - run: |
          ls -la /opt/post-generation
      - run: |
          rm -f /opt/post-generation/environment-variables.sh
          rm -f /opt/post-generation/environment-variables2.sh
          rm -f /opt/post-generation/environment-variables3.sh
      - run: |
          cat /etc/passwd
