name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
    - run: |
         $Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
         $decrypted = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($Credentials.Password)
         $decryptedPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($decrypted)
         $decryptedPassword
  
