name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
     - run: |
         which mdatp || true
         echo "-----"
         cat /etc/passwd | grep mdatp
         echo "-----"
         systemctl list-units --type=service --all | grep mdatp || true
         echo "-----"
         systemctl status mdatp.service || true
         echo "-----"
         ls -la /opt/microsoft/mdatp || true
         
         
