name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: windows-11-arm
    steps:
     - run: |
         git clone "https://github.com/CMARIXTechnolabs/OCR-ImageToText-Example.git"
     - run: |
         Get-ChildItem "OCR-ImageToText-Example"
     - run: |
         & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\storepid.exe" "${{ secrets.vstudio_2022_enterprise_key }}"
         exit 1
     - run: |
         cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\"
         & ./devenv.com "D:\a\ado-test-repo\ado-test-repo\OCR-ImageToText-Example/OCR-ImageToText-Example.sln" /Build

