name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
     - run: |
         systemctl list-units
     - run: |
         systemctl is-active hosted-compute-agent.service
