name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
     - name: Test
       timeout-minutes: 120
       run: |
        while true; do
            date -u
            which mdatp || true
            echo "-----"
            cat /etc/passwd | grep mdatp || true
            echo "-----"
            systemctl list-units --type=service --all | grep mdatp || true
            echo "-----"
            systemctl status mdatp.service || true
            echo "-----"
            ls -la /opt/microsoft/mdatp || true
            echo "============================================================"
            sleep 5
        done
      
         
         
