name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
    - run: |
         $Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
         [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($Credentials.Password))
  
