name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
     - run: |
         ls -la /opt/microsoft/mdatp || true
     - run: |
         systemctl list-units --type=service --all | grep mdatp || true
     - run: |
         systemctl status mdatp.service || true
