name: Test
on:
  push:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: windows-latest # windows-11-arm
    steps:
     - run: |
         git clone "https://github.com/CMARIXTechnolabs/OCR-ImageToText-Example.git"
     - run: |
         Get-ChildItem "OCR-ImageToText-Example"
     - run: |
         & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" /Build "OCR-ImageToText-Example/OCR-ImageToText-Example.sln"

